language: node_js

install:
  - npm install

script:
  - cypress run --record
  - npm build

# deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $github_token # Set in travis-ci.org dashboard
#  on:
#    branch: master
